project:
  type: website
  output-dir: docs

website:
  title: "Daniele Nana Portfolio"
  navbar:
    background: primary
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "À propos"
        href: about.qmd
      - text: "Projets"
        href: projects.qmd
      - text: "Travaux de recherche"
        href: works.qmd
    right:
      - icon: github
        href: https://github.com/Daniele-Nana

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: false
    css: styles.css
